name: 01. Development Environment
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  build:
    defaults:
      run:
        working-directory: examples/Development Environment
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: ./gradlew build
